import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const employees = pgTable('employees', {
  id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), role: text('role').notNull(), team: text('team').notNull().default('Ressources humaines'), status: text('status').notNull().default('Présent'), initials: text('initials').notNull(), color: text('color').notNull().default('bg-[#c6d6ee]'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})
export const departments = pgTable('departments', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull().unique(), manager: text('manager'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const leaveRequests = pgTable('leave_requests', { id: uuid('id').defaultRandom().primaryKey(), employeeId: uuid('employee_id').notNull(), type: text('type').notNull(), startsAt: timestamp('starts_at', { mode: 'date' }).notNull(), endsAt: timestamp('ends_at', { mode: 'date' }).notNull(), status: text('status').notNull().default('En attente'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const attendanceRecords = pgTable('attendance_records', { id: uuid('id').defaultRandom().primaryKey(), employeeId: uuid('employee_id').notNull(), attendanceDate: timestamp('attendance_date', { mode: 'date' }).notNull(), status: text('status').notNull().default('Présent'), checkIn: timestamp('check_in', { withTimezone: true }), checkOut: timestamp('check_out', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const hrTasks = pgTable('hr_tasks', { id: uuid('id').defaultRandom().primaryKey(), title: text('title').notNull(), description: text('description'), assigneeId: uuid('assignee_id'), status: text('status').notNull().default('À faire'), dueDate: timestamp('due_date', { mode: 'date' }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() })
export const employeeRequests = pgTable('employee_requests', { id: uuid('id').defaultRandom().primaryKey(), employeeId: uuid('employee_id'), employeeEmail: text('employee_email').notNull(), type: text('type').notNull(), title: text('title').notNull(), description: text('description'), status: text('status').notNull().default('pending'), adminNote: text('admin_note'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() })
export const appNotifications = pgTable('app_notifications', { id: uuid('id').defaultRandom().primaryKey(), recipientEmail: text('recipient_email').notNull(), title: text('title').notNull(), body: text('body').notNull(), readAt: timestamp('read_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const appMessages = pgTable('app_messages', { id: uuid('id').defaultRandom().primaryKey(), senderEmail: text('sender_email').notNull(), recipientEmail: text('recipient_email').notNull(), body: text('body').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), readAt: timestamp('read_at', { withTimezone: true }) })
export const roles = pgTable('roles', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull().unique(), name: text('name').notNull(), description: text('description'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const permissions = pgTable('permissions', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull().unique(), module: text('module').notNull(), description: text('description') })
export const rolePermissions = pgTable('role_permissions', { roleId: uuid('role_id').notNull(), permissionId: uuid('permission_id').notNull() })
export const employeeProfiles = pgTable('employee_profiles', { id: uuid('id').defaultRandom().primaryKey(), authUserId: text('auth_user_id').notNull().unique(), registrationNumber: text('registration_number').notNull().unique(), firstName: text('first_name').notNull(), lastName: text('last_name').notNull(), departmentId: uuid('department_id'), roleId: uuid('role_id'), jobTitle: text('job_title'), hireDate: timestamp('hire_date', { mode: 'date' }).defaultNow().notNull(), contractType: text('contract_type').notNull().default('CDI'), isActive: text('is_active').notNull().default('true'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() })
export const attendances = pgTable('attendances', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id').notNull(), clockIn: timestamp('clock_in', { withTimezone: true }).notNull(), clockOut: timestamp('clock_out', { withTimezone: true }), status: text('status').notNull().default('PRESENT'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const activityLogs = pgTable('activity_logs', { id: uuid('id').defaultRandom().primaryKey(), userId: text('user_id'), action: text('action').notNull(), entity: text('entity').notNull(), entityId: uuid('entity_id'), ipAddress: text('ip_address'), userAgent: text('user_agent'), details: text('details'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
