'use client'

import { useEffect, useState } from 'react'
import { CalendarDays, CheckCircle2, Clock3, FileText, Menu, MessageSquare, Bell, Plus, ChevronRight, X } from 'lucide-react'

const cards = [
  ['Solde de congés', '0 jour', 'Aucun solde renseigné', CalendarDays],
  ['Présence du jour', 'Non pointé', 'Commencez votre journée', Clock3],
  ['Tâches ouvertes', '0', 'Aucune tâche assignée', CheckCircle2],
]

export function EmployeeDashboard() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [now, setNow] = useState(() => new Date())
  const [notice, setNotice] = useState('')
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer) }, [])
  function announce(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 3000) }
  const nav = ['Mon espace', 'Mes présences', 'Mes congés', 'Mes tâches', 'Mes formations', 'Mes documents', 'Calendrier', 'Messagerie', 'Mon profil']
  return <div className="min-h-screen bg-[#fafafa] text-black">
    {menuOpen && <button aria-label="Fermer le menu" className="fixed inset-0 z-20 bg-black/20 lg:hidden" onClick={() => setMenuOpen(false)}/>} 
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[270px] flex-col border-r border-black/10 bg-white p-5 transition-transform lg:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-10 flex items-center justify-between"><div className="h-16 w-40 overflow-hidden rounded-xl bg-black"><img src="/octoplus-logo.jpeg" alt="Logo OCTOPLUS TECHNOLOGY" className="h-[175%] w-[175%] max-w-none object-contain"/></div><button className="lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Fermer"><X size={20}/></button></div>
      <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-black/35">Mon espace</p>
      <nav className="space-y-1">{nav.map((item, index) => <button key={item} onClick={() => { setMenuOpen(false); index === 0 ? undefined : announce(`${item} sera disponible prochainement.`) }} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm ${index === 0 ? 'bg-[#fff1f1] font-semibold text-[#c62828]' : 'text-black/55 hover:bg-black/[0.03]'}`}>{index === 0 ? <CheckCircle2 size={18}/> : <ChevronRight size={18}/>} {item}</button>)}</nav>
      <div className="mt-auto border-t border-black/10 pt-4"><div className="flex items-center gap-3 rounded-xl bg-[#fafafa] p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#c62828] text-xs font-bold text-white">EM</div><div><p className="text-xs font-semibold">Espace employé</p><p className="text-[11px] text-black/45">Accès personnel</p></div></div></div>
    </aside>
    <main className="lg:ml-[270px]"><header className="flex h-[72px] items-center justify-between border-b border-black/10 bg-white px-5 sm:px-8"><button className="flex h-10 w-10 items-center justify-center rounded-xl border border-black/10 lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Ouvrir le menu"><Menu size={20}/></button><div className="hidden items-center gap-2 text-sm text-black/45 sm:flex"><span className="font-semibold text-black/75">OCTOPLUS TECHNOLOGY</span><ChevronRight size={15}/><span>Mon espace</span></div><div className="flex items-center gap-3"><span className="hidden text-xs text-black/40 md:inline">{now.toLocaleDateString('fr-FR')} · {now.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}</span><button onClick={() => announce('Vous n’avez aucune nouvelle notification.')} className="relative flex h-10 w-10 items-center justify-center rounded-xl border border-black/10" aria-label="Notifications"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#c62828]"/></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#c62828] text-xs font-bold text-white">EM</div></div></header>
      <div className="mx-auto max-w-[1180px] px-5 py-7 sm:px-8 lg:px-10 lg:py-10"><div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 inline-flex rounded-full bg-[#fff1f1] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-[#c62828]">Mon espace</p><h1 className="text-3xl font-bold tracking-[-0.05em]">Bonjour, bienvenue.</h1><p className="mt-2 text-sm text-black/50">Retrouvez vos informations, demandes et activités au même endroit.</p></div><button onClick={() => announce('Votre demande est prête à être créée.')} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#c62828] px-4 text-sm font-semibold text-white"><Plus size={17}/>Nouvelle demande</button></div>
        <section className="grid gap-4 sm:grid-cols-3">{cards.map(([label, value, detail, Icon]) => <div key={label as string} className="rounded-2xl border border-black/10 bg-white p-5 shadow-[0_10px_30px_rgba(0,0,0,0.04)]"><div className="mb-5 flex items-center justify-between"><p className="text-sm font-medium text-black/55">{label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#fff1f1] text-[#c62828]"><Icon size={18}/></span></div><p className="text-2xl font-bold tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs text-black/40">{detail}</p></div>)}</section>
        <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_1fr]"><section className="rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Mes prochaines échéances</h2><p className="mt-1 text-xs text-black/40">Vos rendez-vous et formations à venir</p></div><CalendarDays size={19} className="text-[#c62828]"/></div><div className="rounded-xl border border-dashed border-black/15 p-6 text-center"><p className="text-sm font-semibold">Aucun événement planifié</p><p className="mt-1 text-xs text-black/45">Les prochaines échéances apparaîtront ici.</p></div></section><section className="rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><h2 className="font-semibold">Accès rapides</h2><div className="mt-4 grid gap-2"><button onClick={() => announce('Ouverture de la demande de congé.')} className="flex min-h-12 items-center gap-3 rounded-xl bg-[#fafafa] px-4 text-left text-sm font-medium"><CalendarDays size={18} className="text-[#c62828]"/>Demander un congé</button><button onClick={() => announce('Ouverture de la messagerie.')} className="flex min-h-12 items-center gap-3 rounded-xl bg-[#fafafa] px-4 text-left text-sm font-medium"><MessageSquare size={18} className="text-[#c62828]"/>Écrire à l’administration</button><button onClick={() => announce('Vos documents seront affichés ici.')} className="flex min-h-12 items-center gap-3 rounded-xl bg-[#fafafa] px-4 text-left text-sm font-medium"><FileText size={18} className="text-[#c62828]"/>Voir mes documents</button></div></section></div>
      </div></main>{notice && <div role="status" className="fixed bottom-5 left-1/2 z-50 w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 rounded-xl bg-[#182b31] px-4 py-3 text-center text-sm font-medium text-white shadow-lg">{notice}</div>}
  </div>
}
